### ISSUE TITLE
Parceler warnings with Kotlin data class

### ISSUE THREAD

**Issue by vycius** [vilnius/tvarkau-vilniu#152]
There is a lot of warnings from Parceler when used with Kotlin data class:
```
Warning:Parceler: Reflection is required to access private field: String thumbnail, consider using non-private.
```
Consider moving to another library for better Kotlin support e.g https://github.com/grandstaish/paperparcel

**Comment by mjurkus** [comment]
More info is here: http://grandstaish.github.io/paperparcel/

I don't know... Don't really like extending and implementing interface for each of the models.

**Comment by vycius** [comment]
`Parcelable` is interface on Android. So you need to implement this interface if you want use `Bundle::putParcelable` without any additional methods. 
Parceler needs `@Parcel` annotation, Paperparcel needs `@PaperParcel` annotation.
With Paperparcel there is no `Parcels::wrap` and `Parcels::unwrap`, but you need to extend with `: PaperParcelable` and define `CREATOR` in companion object. KT example https://github.com/grandstaish/paperparcel/blob/master/examples/kotlin-example/src/main/kotlin/nz/bradcampbell/kotlinexample/State.kt

**Comment by mjurkus** [comment]
Irrelevant with Kotlin's `Parcelize`
