### ISSUE TITLE
Problem detail photo hides toolbar

### ISSUE THREAD

**Issue by vycius** [vilnius/tvarkau-vilniu#17]
On some devices problem problem detail photo hides toolbar.
![screenshot from 2016-01-20 20-43-21](https://cloud.githubusercontent.com/assets/3719141/12461381/3b99daba-bfc1-11e5-84a6-929003f71586.png)

**Comment by GediminasZukas** [comment]
@vycius could you name any device model where this bug appears?

**Comment by vycius** [comment]
This issue was pointed out by @narkusv and uploaded to Slack. On my Nexus 5 toolbar seems to work ok. I will try to reproduce this bug on emulators.

**Comment by vycius** [comment]
It seems that neither of us can reproduce this error. I think it has been fixed in one of the PRs related to problem detail. Closing this.
