### ISSUE TITLE
Limit of created problems

### ISSUE THREAD

**Issue by witiokz** [vilnius/tvarkau-vilniu#197]
In my opinion, a number of problems created during lets say an hour should be limited, because very emotional man :) can create many items for the same problem with just different photos or just by taking photos with different angles.

**Comment by Pasalietis** [comment]
And if you go in sleeping area ther's 30 cars parket on the grass, then what?

**Comment by witiokz** [comment]
I don't think all 30 cars would have the same car id (number), so the problem would not be the same.

**Comment by ViliusKraujutis** [comment]
@witiokz, do you have any examples of such situation as you describe?

I think, this might be a very rare scenario, and it would be "cheaper" (timewise) to ignore/remove such reports manually by admins compared to development hours needed to implement such functionality.

Don't you think so? If you agree, please close this issue :)
