### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by ViliusKraujutis** [vilnius/tvarkau-vilniu#2]
I suggest we make package name `lt.vilnius.tvarkau` instead of `uk.co.es4b.tvarkau_vilniu`.

I dislike when small workshops adds their domain in apps they make. Look how it looks in Google Play Store URL:
`https://play.google.com/store/apps/details?id=uk.co.es4b.tvarkau_vilniu`

Instead it could look like this:
`https://play.google.com/store/apps/details?id=lt.vilnius.tvarkau`.

Cons:
All current users will have to reinstall new application.

**Comment by tadaskay** [comment]
Once we launch, we can release an update to the old app with some sort of redirection. Thus it wouldn't be a problem.

Regarding the package, I honestly think your proposal fits better than uk.*

**Comment by ViliusKraujutis** [comment]
And as agreed on Slack [here](https://codeforvilnius.slack.com/archives/tvarkau-vilniu/p1446228463000066) too, I'm closing this issue now.

**Comment by ViliusKraujutis** [comment]
Some reasons against changing the name https://codeforvilnius.slack.com/archives/tvarkau-vilniu/p1447689548000152
