### ISSUE TITLE
Checking for changes when exiting profile screen

### ISSUE THREAD

**Issue by pijusn** [vilnius/tvarkau-vilniu#72]
If you enter your profile screen and exit without modifying anything, you are still prompted about possible data loss. This introduced bad emotions for me as a user. I knew I didn't change anything so it made me think "Did I do anything? Is there some hidden information that was changed?"

I think app should not prompt user if data was not modified. Note I also think dialog should not appear if user was modifying something but the final values are the same as original.

**Comment by inetaa** [comment]
Fully agree!

**Comment by RenatBuga** [comment]
@pijusn Thank you for the suggestion!
The task was created: https://trello.com/c/vvFdtOt9/120-show-dialog-prompting-about-saving-changes-in-my-profile-only-when-changes-were-actually-done

**Comment by inetaa** [comment]
Task already done, the issue is closed.
