### ISSUE TITLE
Reduce menu screen's button sizes

### ISSUE THREAD

**Issue by ViliusKraujutis** [vilnius/tvarkau-vilniu#82]
On smaller screens menu looks like this and there's no way to reduce scroll to see buttons' labels of the bottom row.
![device-2016-10-22-194313](https://cloud.githubusercontent.com/assets/1859636/19620932/d49481aa-988f-11e6-8d84-32075381db52.png)

**Comment by RenatBuga** [comment]
What do you mean by "no way to reduce scroll"? Would it help if the screen is scroll type?
