### ISSUE TITLE
Add screen showing list of problems

### ISSUE THREAD

**Issue by ViliusKraujutis** [vilnius/tvarkau-vilniu#9]
![Design](https://cloud.githubusercontent.com/assets/1859636/11199188/0d1c75be-8cd4-11e5-990d-90d534a4e50e.png)

Design is already created, need to create a screen to showing list of problems.

**Comment by ViliusKraujutis** [comment]
@RenatBuga, do we have a designer in our team? We'll need a placeholder image for this list to be shown while image is being downloaded. Will use this image for that now:
![image](https://cloud.githubusercontent.com/assets/1859636/11200151/23e9afca-8cdc-11e5-9aff-b2bf293d4838.png)

**Comment by RenatBuga** [comment]
The placeholder was added:
https://github.com/RenatBuga/tvarkau-vilniu/commit/673c51d1e776f28ca9cde9af55a2ee4409089d80

**Comment by vycius** [comment]
@RenatBuga can we close this issue ?

**Comment by RenatBuga** [comment]
Yes
